### ISSUE TITLE
Question: Remote connection possibilities

### ISSUE THREAD

**Issue by harshalx** [thomis/sensu-plugins-oracle#1]
Hello, 
Is it possible to add the support of connecting to oracle remotely? I understand that the plugin is meant to run ON the oracle host and hence this does'nt make sense. But, we have some constraints where we have to connect to the DB remotely. Hence, will it be possible to support connection through a full fledged connection string specifying the remote hostname?

**Comment by thomis** [comment]
Hi @harshalx 
This should already work. Plugin is basically passing username/password/dbname or connection string to underlying ruby OCI8 class. See here: http://www.rubydoc.info/gems/ruby-oci8/OCI8%3Ainitialize. Also make sure your tnsname.ora file is configured correctly. You can easily test first via sqlplus in the console and then just pass same values to the plugin. 
All the best,
Thomi
