### ISSUE TITLE
Warning short switch colides with workers switch

### ISSUE THREAD

**Issue by aurelije** [thomis/sensu-plugins-oracle#2]
Both warning and worker option have -w as a short flag, so when someone wants to set warning he will in 99% use short flag and check will fail to issue warning. The workaround is to use --warning as a flag.

**Comment by thomis** [comment]
Hi @aurelije. Yes, you are right and thanks for letting me know. Let me think about your proposal or maybe using a complete different flag which is not colliding. I'll get back to you. thomis.

**Comment by thomis** [comment]
Version 0.6.0 has been released where short worker thread option is now -W (capital w).
